import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/participant.dart';
import '../models/participant_model.dart' as models;

class FirestoreParticipantDatasource {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Get participants by event
  Stream<List<Participant>> getParticipantsByEvent(String eventId) {
    return _firestore
        .collection('participants')
        .where('eventId', isEqualTo: eventId)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => models.ParticipantModel.fromFirestore(
                doc.data() as Map<String, dynamic>, 
                doc.id))
            .toList());
  }

  // Get participants by user
  Stream<List<Participant>> getParticipantsByUser(String userId) {
    return _firestore
        .collection('participants')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => models.ParticipantModel.fromFirestore(
                doc.data() as Map<String, dynamic>, 
                doc.id))
            .toList());
  }

  // Get pending participants
  Stream<List<Participant>> getPendingParticipants() {
    return _firestore
        .collection('participants')
        .where('status', isEqualTo: 'pending')
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => models.ParticipantModel.fromFirestore(
                doc.data() as Map<String, dynamic>, 
                doc.id))
            .toList());
  }

  // Register to event
  Future<void> registerToEvent({
    required String eventId,
    required String userId,
    required String userName,
    required String userEmail,
    String? userPhone,
  }) async {
    final participant = models.ParticipantModel(
      id: '', // Will be auto-generated by Firestore
      eventId: eventId,
      userId: userId,
      userName: userName,
      userEmail: userEmail,
      userPhone: userPhone,
      status: 'pending',
      qrCode: null,
      checkInStatus: false,
      checkInTime: null,
      registeredAt: DateTime.now(),
    );

    await _firestore.collection('participants').add(participant.toFirestore());
  }

  // Check if user is already registered
  Future<bool> isUserRegistered({
    required String eventId,
    required String userId,
  }) async {
    final querySnapshot = await _firestore
        .collection('participants')
        .where('eventId', isEqualTo: eventId)
        .where('userId', isEqualTo: userId)
        .get();
    
    return querySnapshot.docs.isNotEmpty;
  }

  // Approve participant
  Future<void> approveParticipant(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'status': 'approved',
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Reject participant
  Future<void> rejectParticipant(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'status': 'rejected',
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Check-in participant
  Future<void> checkInParticipant(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'checkInStatus': true,
          'checkInTime': FieldValue.serverTimestamp(),
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Cancel registration
  Future<void> cancelRegistration(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .delete();
  }

  // Get participant by QR Code
  Future<Participant?> getParticipantByQRCode(String qrCode) async {
    final querySnapshot = await _firestore
        .collection('participants')
        .where('qrCode', isEqualTo: qrCode)
        .limit(1)
        .get();
    
    if (querySnapshot.docs.isEmpty) {
      return null;
    }

    return models.ParticipantModel.fromFirestore(
      querySnapshot.docs.first.data() as Map<String, dynamic>,
      querySnapshot.docs.first.id,
    );
  }
}