import 'dart:math';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../domain/entities/participant.dart';
import '../models/participant_model.dart';

class FirestoreParticipantDatasource {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final Random _random = Random();

  // Generate unique QR code without UUID package
  String _generateQRCode() {
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final randomNum = _random.nextInt(999999);
    final randomString = _random.nextInt(999999).toString().padLeft(6, '0');
    return 'QR-$timestamp-$randomNum-$randomString';
  }

  // Get participants by event
  Stream<List<Participant>> getParticipantsByEvent(String eventId) {
    return _firestore
        .collection('participants')
        .where('eventId', isEqualTo: eventId)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ParticipantModel.fromFirestore(
                doc.data(), 
                doc.id))
            .toList());
  }

  // Get participants by user
  Stream<List<Participant>> getParticipantsByUser(String userId) {
    return _firestore
        .collection('participants')
        .where('userId', isEqualTo: userId)
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ParticipantModel.fromFirestore(
                doc.data(), 
                doc.id))
            .toList());
  }

  // Get pending participants
  Stream<List<Participant>> getPendingParticipants() {
    return _firestore
        .collection('participants')
        .where('status', isEqualTo: 'pending')
        .snapshots()
        .map((snapshot) => snapshot.docs
            .map((doc) => ParticipantModel.fromFirestore(
                doc.data(), 
                doc.id))
            .toList());
  }

  // Register to event
  Future<void> registerToEvent({
    required String eventId,
    required String userId,
    required String userName,
    required String userEmail,
    String? userPhone,
  }) async {
    final participant = ParticipantModel(
      id: '', // Will be auto-generated by Firestore
      eventId: eventId,
      userId: userId,
      userName: userName,
      userEmail: userEmail,
      userPhone: userPhone,
      status: 'pending',
      qrCode: null,
      checkInStatus: false,
      checkInTime: null,
      registeredAt: DateTime.now(),
    );

    await _firestore.collection('participants').add(participant.toFirestore());
  }

  // Check if user is already registered
  Future<bool> isUserRegistered({
    required String eventId,
    required String userId,
  }) async {
    final querySnapshot = await _firestore
        .collection('participants')
        .where('eventId', isEqualTo: eventId)
        .where('userId', isEqualTo: userId)
        .get();
    
    return querySnapshot.docs.isNotEmpty;
  }

  // Approve participant - AUTO GENERATE QR CODE
  Future<void> approveParticipant(String participantId) async {
    // Generate unique QR code
    final qrCode = _generateQRCode();
    
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'status': 'approved',
          'qrCode': qrCode,
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Reject participant
  Future<void> rejectParticipant(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'status': 'rejected',
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Check-in participant by ID
  Future<void> checkInParticipant(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .update({
          'checkInStatus': true,
          'checkInTime': FieldValue.serverTimestamp(),
          'updatedAt': FieldValue.serverTimestamp(),
        });
  }

  // Check-in participant using QR Code
  Future<void> checkInParticipantByQR(String qrCode) async {
    // Find participant by QR code
    final querySnapshot = await _firestore
        .collection('participants')
        .where('qrCode', isEqualTo: qrCode)
        .limit(1)
        .get();
    
    if (querySnapshot.docs.isEmpty) {
      throw Exception('QR Code tidak valid atau peserta tidak ditemukan');
    }

    final participantDoc = querySnapshot.docs.first;
    final participantData = participantDoc.data();
    
    // Check if already approved
    if (participantData['status'] != 'approved') {
      throw Exception('Peserta belum disetujui admin');
    }

    // Check if already checked in
    if (participantData['checkInStatus'] == true) {
      throw Exception('Peserta sudah melakukan check-in sebelumnya');
    }

    // Do check-in
    await participantDoc.reference.update({
      'checkInStatus': true,
      'checkInTime': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }

  // Cancel registration
  Future<void> cancelRegistration(String participantId) async {
    await _firestore
        .collection('participants')
        .doc(participantId)
        .delete();
  }

  // Get participant by QR Code
  Future<Participant?> getParticipantByQRCode(String qrCode) async {
    final querySnapshot = await _firestore
        .collection('participants')
        .where('qrCode', isEqualTo: qrCode)
        .limit(1)
        .get();
    
    if (querySnapshot.docs.isEmpty) {
      return null;
    }

    return ParticipantModel.fromFirestore(
      querySnapshot.docs.first.data(),
      querySnapshot.docs.first.id,
    );
  }
}