// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm_xQC6g626BhDL-G20R7v-JvrJLWRLXA',
    appId: '1:416676628876:web:95ee8b25b961149136eea9',
    messagingSenderId: '416676628876',
    projectId: 'apa-kek-9abbe',
    authDomain: 'apa-kek-9abbe.firebaseapp.com',
    storageBucket: 'apa-kek-9abbe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4cwLk0DaOWb00w0X2wqFtufweyqab7eY',
    appId: '1:416676628876:android:08461eb14ee0257836eea9',
    messagingSenderId: '416676628876',
    projectId: 'apa-kek-9abbe',
    storageBucket: 'apa-kek-9abbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrQue0bcNchb1QUR3ei5Fq3RQYtmOaFeI',
    appId: '1:416676628876:ios:b9748c1c3b9655bf36eea9',
    messagingSenderId: '416676628876',
    projectId: 'apa-kek-9abbe',
    storageBucket: 'apa-kek-9abbe.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrQue0bcNchb1QUR3ei5Fq3RQYtmOaFeI',
    appId: '1:416676628876:ios:b9748c1c3b9655bf36eea9',
    messagingSenderId: '416676628876',
    projectId: 'apa-kek-9abbe',
    storageBucket: 'apa-kek-9abbe.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm_xQC6g626BhDL-G20R7v-JvrJLWRLXA',
    appId: '1:416676628876:web:77d4b84edc1eef4e36eea9',
    messagingSenderId: '416676628876',
    projectId: 'apa-kek-9abbe',
    authDomain: 'apa-kek-9abbe.firebaseapp.com',
    storageBucket: 'apa-kek-9abbe.firebasestorage.app',
  );

}